// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRDvvoXjuDk-4lXorV-1b7rvq_6GtUmlc',
    appId: '1:366730394698:web:d2b75f631b5e36431a7ab3',
    messagingSenderId: '366730394698',
    projectId: 'gearnest-40d17',
    authDomain: 'gearnest-40d17.firebaseapp.com',
    databaseURL: 'https://gearnest-40d17-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'gearnest-40d17.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7brQTXrSMhzbeJ-vLXVbC2UE9ZwBP5Ko',
    appId: '1:366730394698:android:83ac468715d9fdac1a7ab3',
    messagingSenderId: '366730394698',
    projectId: 'gearnest-40d17',
    databaseURL: 'https://gearnest-40d17-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'gearnest-40d17.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAB3OQ0gWCq_UJw5Up7VqKvlUF8WaI_qao',
    appId: '1:366730394698:ios:c03734fceffeefa31a7ab3',
    messagingSenderId: '366730394698',
    projectId: 'gearnest-40d17',
    databaseURL: 'https://gearnest-40d17-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'gearnest-40d17.firebasestorage.app',
    iosClientId: '366730394698-anda1rkrjomt4b7rfq82j6f1sesk5b2j.apps.googleusercontent.com',
    iosBundleId: 'com.example.event',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAB3OQ0gWCq_UJw5Up7VqKvlUF8WaI_qao',
    appId: '1:366730394698:ios:c03734fceffeefa31a7ab3',
    messagingSenderId: '366730394698',
    projectId: 'gearnest-40d17',
    databaseURL: 'https://gearnest-40d17-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'gearnest-40d17.firebasestorage.app',
    iosClientId: '366730394698-anda1rkrjomt4b7rfq82j6f1sesk5b2j.apps.googleusercontent.com',
    iosBundleId: 'com.example.event',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDRDvvoXjuDk-4lXorV-1b7rvq_6GtUmlc',
    appId: '1:366730394698:web:7711eddea728cdd91a7ab3',
    messagingSenderId: '366730394698',
    projectId: 'gearnest-40d17',
    authDomain: 'gearnest-40d17.firebaseapp.com',
    databaseURL: 'https://gearnest-40d17-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'gearnest-40d17.firebasestorage.app',
  );
}
